export const GET_TODOS_BEGIN = 'GET_TODOS_BEGIN';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';
//
export const GET_TODOS_SORTED_BEGIN = 'GET_TODOS_SORTED_BEGIN';
export const GET_TODOS_SORTED_SUCCESS = 'GET_TODOS_SORTED_SUCCESS';
export const GET_TODOS_SORTED_ERROR = 'GET_TODOS_SORTED_ERROR';
//
export const GET_TODO_ID_SUCCESS = 'GET_TODO_ID_SUCCESS';
//
export const POST_TODO_BEGIN = 'POST_TODO_BEGIN';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
export const POST_TODO_ERROR = 'POST_TODO_ERROR';
//
export const GET_TAGS_BEGIN = 'GET_TAGS_BEGIN';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
//
export const REMOVE_TODO_BEGIN = 'REMOVE_TODO_BEGIN';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
//
export const COMPLETE_TODO_BEGIN = 'COMPLETE_TODO_BEGIN';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_TODO_ERROR = 'COMPLETE_TODO_ERROR';
//
export const RECOVER_TODO_BEGIN = 'RECOVER_TODO_BEGIN';
export const RECOVER_TODO_SUCCESS = 'RECOVER_TODO_SUCCESS';
export const RECOVER_TODO_ERROR = 'RECOVER_TODO_ERROR';
//
export const SORT_TODOS = 'SORT_TODOS';
