export const GET_TODOS_BEGIN = 'GET_TODOS_BEGIN';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR= 'GET_TODOS_ERROR';

export const POST_TODO_BEGIN = 'POST_TODOS_BEGIN';
export const POST_TODO_SUCCESS = 'POST_TODOS_SUCCESS';
export const POST_TODO_ERROR= 'POST_TODOS_ERROR';